### ISSUE TITLE
Register on events

### ISSUE THREAD

**Issue by Kaos1337** [macpie/node-teamspeak-api#1]
Hello,
can I do something to register an event like the join of an user to reply "hello" to him? If yes, can you provide an example?
Thanks.

**Comment by macpie** [comment]
Yes you can look at [Subscribe to events](https://github.com/macpie/node-teamspeak-api#subscribeunsubscribe-to-events) as for the exact event, I am not sure but easy to find out. Just create a listener using `notify` to listen to all events.

Take a look at this [TS3 Manual pdf](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf) and check for `SERVERNOTIFYREGISTER`. You will find the list of things you can subscribe for.

**Comment by Kaos1337** [comment]
Thanks for the answer.
